"""message

Revision ID: 01e03c28d137
Revises: ac41942ff32f
Create Date: 2023-10-09 11:42:33.665494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e03c28d137'
down_revision: Union[str, None] = 'ac41942ff32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_sex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_sex')
    # ### end Alembic commands ###
