"""Message

Revision ID: 064b73a76998
Revises: 59d489c87f64
Create Date: 2023-11-10 10:25:06.907403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064b73a76998'
down_revision: Union[str, None] = '59d489c87f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employe_nation_fkey', 'employe', type_='foreignkey')
    op.create_foreign_key(None, 'employe', 'employe_knowledge', ['knowledge'], ['id'])
    op.drop_column('employe', 'nation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('nation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.create_foreign_key('employe_nation_fkey', 'employe', 'employe_nation', ['nation'], ['id'])
    # ### end Alembic commands ###
