"""Message

Revision ID: 067aec78536e
Revises: 17689c878b78
Create Date: 2023-11-10 10:38:07.670698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067aec78536e'
down_revision: Union[str, None] = '17689c878b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('new_degree', postgresql.ENUM('a', 'b', 'c', 'd', name='employe_new_degree_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe', 'new_degree')
    # ### end Alembic commands ###
