"""Message

Revision ID: 0c6f7b8b54e4
Revises: 064b73a76998
Create Date: 2023-11-10 10:25:47.145628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c6f7b8b54e4'
down_revision: Union[str, None] = '064b73a76998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_nation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_nation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nation', postgresql.ENUM('türkmen', 'özbek', 'rus', 'buluj', 'azerbaýjan', 'gazak', 'ermeni', 'tatar', 'beýleki milletler', name='employe_nation_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employe_nation_pkey')
    )
    # ### end Alembic commands ###
