"""empty message

Revision ID: 0ce9e55b56c4
Revises: be8e586111e3
Create Date: 2023-10-18 12:46:46.308559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce9e55b56c4'
down_revision: Union[str, None] = 'be8e586111e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ManyToManyEmployeEnd_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('end_knowledge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ManyToManyEmployeEnd_knowledge')
    # ### end Alembic commands ###
