"""empty message

Revision ID: 0edfef7c963e
Revises: 4fca5054981f
Create Date: 2023-10-20 10:26:21.558444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0edfef7c963e'
down_revision: Union[str, None] = '4fca5054981f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_professional_education', 'employes')
    op.drop_column('employe_vocational_training', 'employes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_vocational_training', sa.Column('employes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('employe_professional_education', sa.Column('employes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
