"""Message

Revision ID: 17008e2cd7cf
Revises: 067aec78536e
Create Date: 2023-11-10 10:42:07.134023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17008e2cd7cf'
down_revision: Union[str, None] = '067aec78536e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_knowledge')
    op.drop_column('employe', 'knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('knowledge', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('employe_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('knowledge', postgresql.ENUM('ýokary okuw mekdebinden soňky hünäri', 'ýokary hünär', 'orta hünär', 'başlangyç hünär', 'umumy orta', 'esasy orta', name='employe_knowledge_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employe_knowledge_pkey')
    )
    # ### end Alembic commands ###
