"""Message

Revision ID: 1734b053dc62
Revises: 8d35a1ad453b
Create Date: 2023-11-10 10:00:06.910229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1734b053dc62'
down_revision: Union[str, None] = '8d35a1ad453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_sex', 'id1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_sex', sa.Column('id1', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
