"""Message

Revision ID: 17689c878b78
Revises: 7989dc89b527
Create Date: 2023-11-10 10:37:39.735876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17689c878b78'
down_revision: Union[str, None] = '7989dc89b527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_new_degree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_new_degree',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('degree', postgresql.ENUM('Ýolbaşçy', 'Hünärmen', 'Beýleki gullukçylar', 'Işçiler', name='employe_new_degree_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employe_new_degree_pkey')
    )
    # ### end Alembic commands ###
