"""Message

Revision ID: 2a73e5644673
Revises: 0c6f7b8b54e4
Create Date: 2023-11-10 10:26:42.737349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a73e5644673'
down_revision: Union[str, None] = '0c6f7b8b54e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('nation', postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', name='employe_nation_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe', 'nation')
    # ### end Alembic commands ###
