"""message

Revision ID: 3ffa69379f2c
Revises: 01e03c28d137
Create Date: 2023-10-09 11:48:13.469764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffa69379f2c'
down_revision: Union[str, None] = '01e03c28d137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_new_degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_new_degree')
    # ### end Alembic commands ###
