"""empty message

Revision ID: 41e8d36533f0
Revises: 5bed9c20bd72
Create Date: 2023-10-25 12:21:21.689511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41e8d36533f0'
down_revision: Union[str, None] = '5bed9c20bd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe_age_between', 'age_between',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', name='employe_age_between_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe_age_between', 'age_between',
               existing_type=postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', name='employe_age_between_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
