"""message

Revision ID: 48e6b1e0b96e
Revises: cc2f033d0169
Create Date: 2023-10-09 11:17:07.781433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e6b1e0b96e'
down_revision: Union[str, None] = 'cc2f033d0169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_knowledge')
    # ### end Alembic commands ###
