"""empty message

Revision ID: 4ed11c6f5503
Revises: 29e5757b8b37
Create Date: 2023-10-25 13:03:12.405472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed11c6f5503'
down_revision: Union[str, None] = '29e5757b8b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_age_between', 'age_between')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_age_between', sa.Column('age_between', postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', name='employe_age_between_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
