"""empty message

Revision ID: 4fca5054981f
Revises: b0cf65c8862f
Create Date: 2023-10-20 10:15:41.223674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fca5054981f'
down_revision: Union[str, None] = 'b0cf65c8862f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ManyToManyEmploye_professional_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('professional_education', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ManyToManyEmploye_vocational_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('vocational_training', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ManyToManyEmploye_vocational_training')
    op.drop_table('ManyToManyEmploye_professional_education')
    # ### end Alembic commands ###
