"""Message

Revision ID: 52df6843ddc5
Revises: e089f5739cb9
Create Date: 2023-11-10 10:17:46.421182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52df6843ddc5'
down_revision: Union[str, None] = 'e089f5739cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_age_between')
    op.drop_column('employe', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('employe_age_between',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age_between', postgresql.ENUM('18 ýaşa çenli', '18-20 ýaş', '21-22 ýaş', '23-24 ýaş', '25-29 ýaş', '30-34 ýaş', '35-39 ýaş', '40-49 ýaş', name='employe_age_between_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employe_age_between_pkey')
    )
    # ### end Alembic commands ###
