"""Add new field to User model

Revision ID: 544ed2b75a58
Revises: a755b171fbbb
Create Date: 2023-10-11 10:10:07.015096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544ed2b75a58'
down_revision: Union[str, None] = 'a755b171fbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user')
    # ### end Alembic commands ###
