"""empty message

Revision ID: 6948dc1f29c9
Revises: a5bdd3fe8098
Create Date: 2023-10-25 13:20:35.830304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6948dc1f29c9'
down_revision: Union[str, None] = 'a5bdd3fe8098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe_nation', 'nation',
               existing_type=postgresql.ENUM('türkmen', 'özbek', 'rus', 'buluj', 'azerbaýjan', 'gazak', 'ermeni', 'tatar', 'beýleki milletler', name='employe_nation_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe_nation', 'nation',
               existing_type=postgresql.ENUM('türkmen', 'özbek', 'rus', 'buluj', 'azerbaýjan', 'gazak', 'ermeni', 'tatar', 'beýleki milletler', name='employe_nation_enum'),
               nullable=False)
    # ### end Alembic commands ###
