"""message

Revision ID: 8090ec67c634
Revises: dbfd4f4602dc
Create Date: 2023-10-09 11:00:55.979576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8090ec67c634'
down_revision: Union[str, None] = 'dbfd4f4602dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_end_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_part', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_end_knowledge')
    # ### end Alembic commands ###
