"""Message

Revision ID: 85efacd2ea25
Revises: 17008e2cd7cf
Create Date: 2023-11-10 10:42:33.232001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85efacd2ea25'
down_revision: Union[str, None] = '17008e2cd7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('knowledge', postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', name='employe_knowledge_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe', 'knowledge')
    # ### end Alembic commands ###
