"""Message

Revision ID: 8d35a1ad453b
Revises: 831c4becfcc5
Create Date: 2023-11-10 09:58:54.401592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d35a1ad453b'
down_revision: Union[str, None] = '831c4becfcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_sex', sa.Column('id1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_sex', 'id1')
    # ### end Alembic commands ###
