"""Message

Revision ID: 9bbbf2acb092
Revises: 99cb02d5af93
Create Date: 2023-11-10 09:49:42.026521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbbf2acb092'
down_revision: Union[str, None] = '99cb02d5af93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_new_degree', 'degree')
    op.drop_column('employe_sex', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_sex', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employe_new_degree', sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
