"""empty message

Revision ID: a5bdd3fe8098
Revises: 571d65630dd4
Create Date: 2023-10-25 13:09:11.952366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5bdd3fe8098'
down_revision: Union[str, None] = '571d65630dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_age_between', sa.Column('age_between', postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', name='employe_age_between_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_age_between', 'age_between')
    # ### end Alembic commands ###
