"""message

Revision ID: ac41942ff32f
Revises: bd99fc6b14ae
Create Date: 2023-10-09 11:37:58.017758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac41942ff32f'
down_revision: Union[str, None] = 'bd99fc6b14ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_professional_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_education', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_professional_education')
    # ### end Alembic commands ###
