"""empty message

Revision ID: b45edb7586a6
Revises: 7efb670289be
Create Date: 2023-10-25 11:04:03.450855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b45edb7586a6'
down_revision: Union[str, None] = '7efb670289be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_age_between', sa.Column('age_between', postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', name='employe_age_between_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_age_between', 'age_between')
    # ### end Alembic commands ###
