"""empty message

Revision ID: b707282e2234
Revises: a07d708fa1e8
Create Date: 2023-10-23 13:15:27.163761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b707282e2234'
down_revision: Union[str, None] = 'a07d708fa1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_age_between', 'age_between')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_age_between', sa.Column('age_between', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
