"""Message

Revision ID: bd0556495f81
Revises: c4642ba2953a
Create Date: 2023-11-10 10:32:54.655166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd0556495f81'
down_revision: Union[str, None] = 'c4642ba2953a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('sex', postgresql.ENUM('a', 'b', 'c', name='employe_sex_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe', 'sex')
    # ### end Alembic commands ###
