"""message

Revision ID: bd99fc6b14ae
Revises: 1f6b162ed15f
Create Date: 2023-10-09 11:27:36.300381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd99fc6b14ae'
down_revision: Union[str, None] = '1f6b162ed15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe_vocational_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocational_training', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_vocational_training')
    # ### end Alembic commands ###
