"""Add new field to User model

Revision ID: be8e586111e3
Revises: 2112f293a4ff
Create Date: 2023-10-11 13:03:54.003361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be8e586111e3'
down_revision: Union[str, None] = '2112f293a4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_end_knowledge', sa.Column('employes', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('employe_end_knowledge', 'emploes')
    op.add_column('employe_professional_education', sa.Column('employes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('employe_vocational_training', sa.Column('employes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_vocational_training', 'employes')
    op.drop_column('employe_professional_education', 'employes')
    op.add_column('employe_end_knowledge', sa.Column('emploes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('employe_end_knowledge', 'employes')
    # ### end Alembic commands ###
