"""empty message

Revision ID: c06872ecb4b8
Revises: 0ce9e55b56c4
Create Date: 2023-10-18 13:02:44.452629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06872ecb4b8'
down_revision: Union[str, None] = '0ce9e55b56c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ManyToManyEmployeEnd_knowledge')
    op.add_column('employe', sa.Column('rer', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employe', 'employe_end_knowledge', ['rer'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_column('employe', 'rer')
    op.create_table('ManyToManyEmployeEnd_knowledge',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ManyToManyEmployeEnd_knowledge_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('employe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_knowledge', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ManyToManyEmployeEnd_knowledge_pkey')
    )
    # ### end Alembic commands ###
