"""Message

Revision ID: c4642ba2953a
Revises: 2a73e5644673
Create Date: 2023-11-10 10:32:27.585083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4642ba2953a'
down_revision: Union[str, None] = '2a73e5644673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_sex')
    op.drop_column('employe', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('sex', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('employe_sex',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sex', postgresql.ENUM('erkek', 'zenan', 'başga', name='employe_sex_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employe_sex_pkey')
    )
    # ### end Alembic commands ###
