"""message

Revision ID: cd98e8e1ae3c
Revises: 3ffa69379f2c
Create Date: 2023-10-09 12:24:54.585925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd98e8e1ae3c'
down_revision: Union[str, None] = '3ffa69379f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_surname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe')
    # ### end Alembic commands ###
