"""message

Revision ID: d1d6c027bb61
Revises: 1aa69bfbd0a6
Create Date: 2023-10-10 10:35:37.794115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d6c027bb61'
down_revision: Union[str, None] = '1aa69bfbd0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe', sa.Column('nation', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('sex', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('new_degree', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('end_knowledge', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('knowledge', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('vocational_training', sa.Integer(), nullable=False))
    op.add_column('employe', sa.Column('professional_education', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employe', 'employe_new_degree', ['new_degree'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_nation', ['nation'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_professional_education', ['professional_education'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_sex', ['sex'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_age_between', ['age'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_end_knowledge', ['end_knowledge'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_knowledge', ['knowledge'], ['id'])
    op.create_foreign_key(None, 'employe', 'employe_vocational_training', ['vocational_training'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_constraint(None, 'employe', type_='foreignkey')
    op.drop_column('employe', 'professional_education')
    op.drop_column('employe', 'vocational_training')
    op.drop_column('employe', 'knowledge')
    op.drop_column('employe', 'end_knowledge')
    op.drop_column('employe', 'new_degree')
    op.drop_column('employe', 'sex')
    op.drop_column('employe', 'age')
    op.drop_column('employe', 'nation')
    # ### end Alembic commands ###
