"""Message

Revision ID: e089f5739cb9
Revises: 0577bbe9dcf4
Create Date: 2023-11-10 10:04:37.611030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e089f5739cb9'
down_revision: Union[str, None] = '0577bbe9dcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employe_new_degree', sa.Column('degree', postgresql.ENUM('a', 'b', 'c', 'd', name='employe_new_degree_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employe_new_degree', 'degree')
    # ### end Alembic commands ###
