"""empty message

Revision ID: e4726ea713a3
Revises: 248c9754bca7
Create Date: 2023-10-25 12:40:35.003033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4726ea713a3'
down_revision: Union[str, None] = '248c9754bca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe_knowledge', 'knowledge',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', name='employe_knowledge_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe_knowledge', 'knowledge',
               existing_type=postgresql.ENUM('a', 'b', 'c', 'd', 'e', 'f', name='employe_knowledge_enum'),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
