"""Add new field to User model

Revision ID: f6bd73ac85f7
Revises: d1a43c131695
Create Date: 2023-10-11 10:46:36.676865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bd73ac85f7'
down_revision: Union[str, None] = 'd1a43c131695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_user_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_fkey', 'roles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
